### ISSUE TITLE
data-preparation graph issue

### ISSUE THREAD

**Issue by tiffanalin** [tiffanalin/dashboardteam5#17]
when the app loads, the graph displayed adds a "0" continent to the legend and graphs. is this a result from interpolation? 

![Screenshot 2023-04-01 224152](https://user-images.githubusercontent.com/115715961/229313141-e27cf1bc-e26e-46ef-a78a-dc28f77aa7d1.jpg)

**Comment by halaalbahloul** [comment]
Practeclly, there was some rows with Nan values in the continent column. 
![image](https://user-images.githubusercontent.com/38258858/229344167-1cb66112-10ae-482d-9a84-2098dc0a2f30.png)

In the first version, we just drop all the nan values so we didn't see those rows
Now, we filled them by 0 instead of dropping them and that is why you see these continent.
_we can fill this coulmn with "**No continent**" or fill depending on the **iso_code**._

**Comment by tiffanalin** [comment]
Ah, I understand now. We only need location data, not country data. So, once that is changed, the 0's will resolve. I was testing things out in a jupyter notebook, so I have a cleaned dataset like this: 
![Screenshot 2023-04-02 123705](https://user-images.githubusercontent.com/115715961/229347798-9ba7d61e-fab1-43a3-8ee1-e19cff7029a3.jpg)

*location column*: dropped some rows that were not countries (ex: 'high income')
*cases & deaths columns*: replaced missing values with 0's, the missing values were due to no cases yet.
*whole df*: normalized to population (per 1,000,000 people)

**Comment by halaalbahloul** [comment]
which country data? I think we have iso_code, continent, location.
we will use also the continent for some graphs so I think it is better to map it and refill it correctly .
for numerical missing data, I have fill it using **pandas.DataFrame.interpolate** . I think you can normalize the final df after cleaning.
